### ISSUE TITLE
commit / pull request conventions

### ISSUE THREAD

**Issue by 100ideas** [websemantics/awesome-synthetic-biology#3]
I assume each commit should only add one new (proposed) link - right?

Would you prefer each commit be contributed in its own pull request? Or is it ok to add, say, 5 new links in a section such as Hardware, each in its own commit, then issue a single pull request?

thanks

**Comment by websemantics** [comment]
First, many thanks for your PR, great resource, 

I haven't thought about this actually, but in these early days, I would be more than happy with any contributions, including n # of new links :)

Very interesting topic and exciting developments are happening continuously,
